unseal-hotp: ensure /boot mounted before checking HOTP secret
If /boot isn't mounted, we can't read the HOTP secret, so no
point in reading from the TPM, or in the non-TPM case, reading
the firmware from flash (which is slow). This speeds up
getting to the main menu in the case of an inaccessible
or non-existant /boot, and maintains the warning condition
from not being able to validate the HOTP.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

diff --git a/initrd/bin/unseal-hotp b/initrd/bin/unseal-hotp
--- a/initrd/bin/unseal-hotp
+++ b/initrd/bin/unseal-hotp
@@ -17,6 +17,26 @@ mount_boot_or_die()
   fi
 }
 
+# Store counter in file instead of TPM for now, as it conflicts with Heads
+# config TPM counter as TPM 1.2 can only increment one counter between reboots
+# get current value of HOTP counter in TPM, create if absent
+mount_boot_or_die
+
+#check_tpm_counter $HOTP_COUNTER hotp \
+#|| die "Unable to find/create TPM counter"
+#counter="$TPM_COUNTER"
+#
+#counter_value=$(read_tpm_counter $counter | cut -f2 -d ' ' | awk 'gsub("^000e","")')
+#
+
+counter_value=$(cat $HOTP_COUNTER)
+
+if [ "$counter_value" == "" ]; then
+  die "Unable to read HOTP counter"
+fi
+
+#counter_value=$(printf "%d" 0x${counter_value})
+
 if [ "$CONFIG_TPM" = "y" ]; then
   tpm nv_readvalue \
     -in 4d47 \
@@ -41,26 +61,6 @@ else
     flash.sh -s ${ROM_IMAGE} | cut -c 1-20 | tr -d '\n' > $HOTP_SECRET
   fi
 fi
-
-# Store counter in file instead of TPM for now, as it conflicts with Heads
-# config TPM counter as TPM 1.2 can only increment one counter between reboots
-# get current value of HOTP counter in TPM, create if absent
-mount_boot_or_die
-
-#check_tpm_counter $HOTP_COUNTER hotp \
-#|| die "Unable to find/create TPM counter"
-#counter="$TPM_COUNTER"
-#
-#counter_value=$(read_tpm_counter $counter | cut -f2 -d ' ' | awk 'gsub("^000e","")')
-#
-
-counter_value=$(cat $HOTP_COUNTER)
-
-if [ "$counter_value" == "" ]; then
-  die "Unable to read HOTP counter"
-fi
-
-#counter_value=$(printf "%d" 0x${counter_value})
 
 if ! hotp $counter_value < "$HOTP_SECRET"; then
 	rm -f "$HOTP_SECRET"
