Add .circleci/config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,38 @@
-version: 2
+version: 2.1
+
+commands:
+  build_board:
+    parameters:
+      target:
+        type: string
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract
+      - run:
+          name: Make Board
+          command: |
+            rm -rf build/<<parameters.target>>/* build/log/* && make CPUS=16 V=1 BOARD=<<parameters.target>> || touch ./tmpDir/failed_build
+          no_output_timeout: 3h
+      - run:
+          name: Output build failing logs
+          command: |
+            if [[ -f ./tmpDir/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
+      - run:
+          name: Output hashes
+          command: |
+            cat build/<<parameters.target>>/hashes.txt \
+      - run:
+          name: Archiving build logs.
+          command: |
+             tar zcvf build/<<parameters.target>>/logs.tar.gz build/log/*
+      - store_artifacts:
+          path: build/<<parameters.target>>
+
 jobs:
-  build:
+  prep_env:
     docker:
       - image: debian:10
     steps:
@@ -8,7 +40,7 @@ jobs:
           name: Install dependencies
           command: |
             apt update
-            apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync
+            apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract
       - checkout
 
       - run:
@@ -17,23 +49,155 @@ jobs:
             git reset --hard "$CIRCLE_SHA1" \
 
       - run:
-          name: Creating all modules and patches digest
+          name: Make tmp dir
           command: |
-            find ./patches/ ./modules/ -type f | sort -h |xargs sha256sum > /tmp/all_modules_and_patches.sha256sums \
+            mkdir ./tmpDir \
 
       - run:
-          name: Creating musl-cross-make and musl-cross-make patches digest
+          name: Creating all modules and patches digest (All modules cache digest)
           command: |
-            find modules/musl-cross* -type f | sort -h | xargs sha256sum > /tmp/musl-cross_module_and_patches.sha256sums \
+            find ./patches/ ./modules/ -type f | sort -h |xargs sha256sum > ./tmpDir/all_modules_and_patches.sha256sums \
 
+      - run:
+          name: Creating coreboot (and associated patches) and musl-cross-make modules digest (musl-cross-make and coreboot cache digest)
+          command: |
+            find ./modules/coreboot ./modules/musl-cross* ./patches/coreboot* -type f | sort -h | xargs sha256sum > ./tmpDir/coreboot_musl-cross.sha256sums \
+
+      - run:
+          name: Creating musl-cross-make and musl-cross-make patches digest (musl-cross-make cache digest)
+          command: |
+            find modules/musl-cross* -type f | sort -h | xargs sha256sum > ./tmpDir/musl-cross.sha256sums \
 
       - restore_cache:
           keys:
-            #Restore existing cache for modules checksums validated to be exactly the same as in github current commit
-            - heads-modules-and-patches-{{ checksum "/tmp/all_modules_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
-            #If precedent fails. Restore cache for musl-cross module checksum validated to be exactly the same as in github current commit
-            - heads-cross-musl-{{ checksum "/tmp/musl-cross_module_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+            #Restore existing cache for matching modules digest, validated to be exactly the same as in github current commit.
+            #This cache was made on top of below caches, if previously existing. If no module definition changed, we reuse this one. Otherwise...
+            - heads-modules-and-patches-{{ checksum "./tmpDir/all_modules_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+            #If precedent cache not found, restore cache for coreboot module (and patches) and musl-cross-make digests (bi-yearly modified)
+            #Otehrwise....
+            - heads-coreboot-musl-cross-{{ checksum "./tmpDir/coreboot_musl-cross.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+            #If precedent cache not found. Restore cache for musl-cross-make module digest (rarely modified).
+            #Otherwise, we build cleanly.
+            - heads-musl-cross-{{ checksum "./tmpDir/musl-cross.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+      - run:
+          name: Download / extract Purism librem_skl blobs
+          command: |
+            ./blobs/librem_skl/get_blobs.sh
 
+      - run:
+          name: Download / extract Purism librem_kbl blobs
+          command: |
+            ./blobs/librem_kbl/get_blobs.sh
+
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - .
+
+  build_and_persist:
+    docker:
+      - image: debian:10
+    parameters:
+      target:
+        type: string
+    steps:
+      - attach_workspace:
+          at: ~/
+      - build_board:
+          target: <<parameters.target>>
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - .
+
+  build:
+    docker:
+      - image: debian:10
+    parameters:
+      target:
+        type: string
+    steps:
+      - attach_workspace:
+          at: ~/
+      - build_board:
+          target: <<parameters.target>>
+
+  save_cache:
+    docker:
+      - image: debian:10
+    steps:
+      - attach_workspace:
+          at: ~/
+      - save_cache:
+          #Generate cache for the same musl-cross module definition if hash is not previously existing
+          key: heads-musl-cross-{{ checksum "./tmpDir/musl-cross.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+          paths:
+            - crossgcc
+            - build/musl-cross-*
+      - save_cache:
+          #Generate cache for the same coreboot mnd musl-cross-make modules definition if hash is not previously existing
+          key: heads-coreboot-musl-cross-{{ checksum "./tmpDir/coreboot_musl-cross.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+          paths:
+            - build/coreboot-*
+            - crossgcc
+            - build/musl-cross-*
+      - save_cache:
+          #Generate cache for the exact same modules definitions if hash is not previously existing
+          key: heads-modules-and-patches-{{ checksum "./tmpDir/all_modules_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
+          paths:
+            - packages
+            - crossgcc
+            - build
+            - install
+
+workflows:
+  version: 2
+  build_and_test:
+    jobs:
+      - prep_env
+
+# Below, sequentially build one board for each coreboot
+# version. The last board in the sequence is the dependency
+# for the parallel boards built at the end, and also save_cache.
+
+      # Coreboot 4.8.1
+      - build_and_persist:
+          name: qemu-coreboot
+          target: qemu-coreboot
+          requires:
+            - prep_env
+
+      - build_and_persist:
+          name: librem_13v2
+          target: librem_13v2
+          requires:
+            - qemu-coreboot
+      
+      # Coreboot 4.11
+      - build_and_persist:
+          name: librem_l1um
+          target: librem_l1um
+          requires:
+            - librem_13v2
+
+      # Coreboot Purism repo
+      - build_and_persist:
+          name: librem_mini
+          target: librem_mini
+          requires:
+            - librem_l1um
+
+      - build:
+          name: librem_14
+          target: librem_14
+          requires:
+            - librem_mini
+
+########################
+########################
+###    OLD STUFF     ###
+########################
+########################
 # linuxboot steps need something to pass in the kernel header path
 # skipping for now
 #      - run:
@@ -50,7 +214,7 @@ jobs:
 #          command: |
 #            ./build/make-4.2.1/make \
 #                CROSS=/cross/bin/x86_64-linux-musl- \
-#                CPUS=4 \
+#                CPUS=16 \
 #                V=1 \
 #                BOARD=qemu-linuxboot \
 #
@@ -58,225 +222,3 @@ jobs:
 #          path: build/qemu-linuxboot/linuxboot.rom
 #      - store-artifacts:
 #          path: build/qemu-linuxboot/hashes.txt
-
-      - run:
-          name: librem_l1um
-          command: |
-            rm -rf build/librem_l1um/* build/log/* && make CPUS=4 V=1 BOARD=librem_l1um || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs 
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
-      - run:
-          name: Output librem_l1um hashes
-          command: |
-            cat build/librem_l1um/hashes.txt \
-      - run:
-          name: Archiving build logs for librem_l1um
-          command: |
-             tar zcvf build/librem_l1um/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/librem_l1um
-
-      - run:
-          name: librem_mini
-          command: |
-            rm -rf build/librem_mini/* build/log/* && make CPUS=4 V=1 BOARD=librem_mini || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output librem_mini hashes
-          command: |
-            cat build/librem_mini/hashes.txt \
-      - run:
-          name: Archiving build logs for librem_mini
-          command: |
-             tar zcvf build/librem_mini/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/librem_mini
-
-      - run:
-          name: x230-flash
-          #We delete build/make-4.2.1/ directory until issue #799 is fixed.
-          command: |
-            rm -rf build/x230-flash/* build/log/* && make CPUS=4 V=1 BOARD=x230-flash || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output x230-flash hashes
-          command: |
-            cat build/x230-flash/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-flash
-          command: |
-             tar zcvf build/x230-flash/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-flash
-
-      - run:
-          name: t430-flash
-          command: |
-            rm -rf build/t430-flash/* build/log/* && make CPUS=4 V=1 BOARD=t430-flash || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output t430-flash hashes
-          command: |
-            cat build/t430-flash/hashes.txt \
-      - run:
-          name: Archiving build logs for t430-flash
-          command: |
-             tar zcvf build/t430-flash/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/t430-flash
-
-      - run:
-          name: t430
-          command: |
-            rm -rf build/t430/* build/log/* && make CPUS=4 V=1 BOARD=t430 || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output t430 hashes
-          command: |
-            cat build/t430/hashes.txt \
-      - run:
-          name: Archiving build logs for t430
-          command: |
-             tar zcvf build/t430/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/t430
-
-      - run:
-          name: x230
-          command: |
-            rm -rf build/x230/* build/log/* && make CPUS=4 V=1 BOARD=x230 || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output x230 hashes
-          command: |
-            cat build/x230/hashes.txt \
-      - run:
-          name: Archiving build logs for x230
-          command: |
-             tar zcvf build/x230/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230
-
-      - run:
-          name: x230-hotp-verification
-          command: |
-            rm -rf build/x230-hotp-verification/* build/log/* && make CPUS=4 V=1 BOARD=x230-hotp-verification || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output x230-hotp-verification hashes
-          command: |
-            cat build/x230-hotp-verification/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-hotp-verification
-          command: |
-             tar zcvf build/x230-hotp-verification/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-hotp-verification
-
-      - run:
-          name: x230-nkstorecli
-          command: |
-            rm -rf build/x230-nkstorecli/* build/log/* && make CPUS=4 V=1 BOARD=x230-nkstorecli || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output x230-nkstorecli hashes
-          command: |
-            cat build/x230-nkstorecli/hashes.txt \
-      - run:
-          name: Archiving build logs for x230-nkstorecli
-          command: |
-             tar zcvf build/x230-nkstorecli/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/x230-nkstorecli
-
-      - run:
-          name: qemu-coreboot
-          command: |
-            rm -rf build/qemu-coreboot/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output qemu-coreboot hashes
-          command: |
-             cat build/qemu-coreboot/hashes.txt \
-      - run:
-          name: Archiving build logs for qemu-coreboot
-          command: |
-             tar zcvf build/qemu-coreboot/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/qemu-coreboot
-
-      - run:
-          name: qemu-coreboot-fbwhiptail
-          command: |
-            rm -rf build/qemu-coreboot-fbwhiptail/* build/log/* && make CPUS=4 V=1 BOARD=qemu-coreboot-fbwhiptail || touch /tmp/failed_build
-          no_output_timeout: 3h
-      - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
-      - run:
-          name: Output qemu-coreboot-fbwhiptail hashes
-          command: |
-             cat build/qemu-coreboot-fbwhiptail/hashes.txt \
-      - run:
-          name: Archiving build logs for qemu-coreboot-fbwhiptail
-          command: |
-             tar zcvf build/qemu-coreboot-fbwhiptail/logs.tar.gz build/log/*
-      - store-artifacts:
-          path: build/qemu-coreboot-fbwhiptail
-
-      - save_cache:
-          #Generate cache for the same musl-cross module definition if hash is not previously existing
-          key: heads-cross-musl-{{ checksum "/tmp/musl-cross_module_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
-          paths:
-            - crossgcc
-            - build/musl-cross-*
-
-      - save_cache:
-          #Generate cache for the exact same modules definitions if hash is not previously existing
-          key: heads-modules-and-patches-{{ checksum "/tmp/all_modules_and_patches.sha256sums" }}{{ .Environment.CACHE_VERSION }}
-          paths:
-            - packages
-            - crossgcc
-            - build
-
-workflows:
-  version: 2
-  build_and_test:
-    jobs:
-      - build
